### ISSUE TITLE
Scala 2.12 version?

### ISSUE THREAD

**Issue by fsvehla** [nrinaudo/kantan.xpath#17]
Any rough idea if this will be hard?

**Comment by nrinaudo** [comment]
I should communicate more. This is actually already done and available as a snapshot release. I still have a few bits and bobs to tidy up (mostly documentation to write) before an official release, but if you want to have an early taste, you can update to version `0.1.8-SNAPSHOT`.

If you don't already have the sonatype snapshot resolver in your build, you'll also need to add the following line to your `build.sbt` file:

```scala
resolvers := Seq(Resolver.sonatypeRepo("snapshots"))
```

Note that for this kind of question, you're probably going to get better / faster answers on the [gitter](https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwiSucyil73QAhUGtBoKHURaDM8QFggdMAA&url=https%3A%2F%2Fgitter.im%2Fnrinaudo%2Fkantan.xpath&usg=AFQjCNHgWB2jncHSGqVJZysCgaiXfH57IA) channel.

**Comment by nrinaudo** [comment]
Official artifacts for 0.1.8 have been published and should make their ways to maven central within the hour.
