### ISSUE TITLE
support for xpath for nth element

### ISSUE THREAD

**Issue by msillence** [nrinaudo/kantan.xpath#22]
Hi,

Thanks for the library, I'm trying to extract specific elements in a list of results:
e.g. 
`  <a><b>1</b><c>2</c></a>`

/a/b[0] should yield 1

There are some examples of list processing here: http://alvinalexander.com/scala/how-extract-data-array-xml-elements-xpath-scala

**Comment by nrinaudo** [comment]
I'm not entirely sure what you mean that. You can already evaluate an XPath expression into a `List[A]`, is that what you need? Something like this:

```scala
val res: List[Int] = "<a><b>1</b><c>2</c></a>".unsafeEvalXPath[List[Int]]("/a/b")
```

You can then do whatever you want with `res`, such as retrieve its head.

If that's what you mean, it's already supported (and, I thought, clearly documented). If not, could you give a concrete example of what you have in mind?

**Comment by msillence** [comment]
Ahh sorry the example should have been:
`<a><b>1</b><b>2</b></a>`

where I only want the first result of a/b i.e. "1" and not the second value "2"

**Comment by msillence** [comment]
Ideally I'd also like to be able to do paths after the index of the select a/b[0]/@id

**Comment by nrinaudo** [comment]
Sure, that's a normal XPath expression, and the full XPath specification should be supported:

```scala
scala> "<a><b>1</b><b>2</b></a>".unsafeEvalXPath[Int](xp"/a/b[1]")
res1: Int = 1

scala> "<a><b id='1'></b><b id='2'></b></a>".unsafeEvalXPath[Int](xp"/a/b[1]/@id")
res2: Int = 1
```

Note: the only thing wrong with your query is that XPath is indexed from 1 and not 0.

**Comment by nrinaudo** [comment]
I'm going to close this, since you're asking for help and not reporting an issue.

Issues are really meant for feature requests or bug reports, not to request personalised help with a library. kantan.xpath has a [gitter chatroom](https://gitter.im/nrinaudo/kantan.xpath), which is a much better place to look for that kind of help.

**Comment by msillence** [comment]
Thank you, really sorry I forgot xpath was 1 based index, I thought that it wasn't supported.

**Comment by nrinaudo** [comment]
Absolutely no problem. It'd be surprising if you found a bug in the XPath implementation, since I'm basically just wrapping the Java one :)
