### ISSUE TITLE
parse a document and apply an xpath in two separate steps

### ISSUE THREAD

**Issue by dportabella** [nrinaudo/kantan.xpath#31]
this reads, parses and applies an xpath:
`new URI("http://some.server.com").evalXPath[List[Int]](xp"//h1/span[@class='num']")`

how can i divide this into two steps?
```
val doc = parse(new URI("http://some.server.com"))
doc.evalXPath[List[Int]](xp"//h1/span[@class='num']")
```

Looking at the source code, I see `XmlSource.fromResource` and other methods, but I don't see how to use it. I didn't find this use case in the documentation neither.

**Comment by nrinaudo** [comment]
The first step is turning "something" into a `Node`. This is achieved through the `XmlSource` typeclass, with some documentation [here](http://nrinaudo.github.io/kantan.xpath/tut/xml_sources.html). `URI` already has an instance, so you're good to go.

You can then summon the corresponding instance and call [`asNode`](http://nrinaudo.github.io/kantan.xpath/api/kantan/xpath/XmlSource.html#asNode(a:A):kantan.xpath.ParseResult[kantan.xpath.Node]) on it:

```scala
XmlSource[URI].asNode(new URI("http://some.server.com"))
```

You can also use the dedicated syntax for that, if this is too boilerplatey for you:

```scala
import kantan.xpath.ops._

new URI("http://some.server.com").asNode
```

You can then directly call [`evalXPath`](http://nrinaudo.github.io/kantan.xpath/api/kantan/xpath/ops/XmlSourceOps.html#evalXPath[B](expr:kantan.xpath.XPathExpression)(implicitevidence$3:kantan.xpath.Compiler[B]):kantan.xpath.XPathResult[B]) on a node:

```scala
import kantan.xpath.ops._

val node: Node = ???

node.evalXPath[List[Int]](xp"//h1/span[@class='num']")
```

**Comment by dportabella** [comment]
cool, thx!
I would add this to the doc, as it is a basic use case and it is not easy to understand from [here](http://nrinaudo.github.io/kantan.xpath/tut/xml_sources.html).
