### ISSUE TITLE
Scala.js support discussion

### ISSUE THREAD

**Issue by bbarker** [nrinaudo/kantan.xpath#35]
I'm curious what would be needed to support Scala.js - it looks like https://github.com/mdedetrich/soda-time might be a suitable alternative to JodaTime, for starters.

**Comment by nrinaudo** [comment]
Honestly, an act from god. Kantan.xpath relies on the JVM's XPath implementation, which isn't available in scala.js. Sorry :/

**Comment by bbarker** [comment]
Ah, I see - I'll close for now then, thanks!

**Comment by nrinaudo** [comment]
If you know of a good xpath lib that I could use for the scala.js module though, feel free to reopen. I’d love to have scala.js support!

**Comment by bbarker** [comment]
Would creating an interface API that can use JVM's XPath implementation on the JVM and something like https://github.com/ilinsky/jquery-xpath on JS be a viable option?

**Comment by nrinaudo** [comment]
It absolutely could, thanks!
