### ISSUE TITLE
XmlSource fails to properly handle XML encoding

### ISSUE THREAD

**Issue by nigredo-tori** [nrinaudo/kantan.xpath#82]
XML has its own means of signaling XML encoding (through `<?xml encoding="..."?>`). `org.xml.sax.InputSource` supports this, but **only for `InputStream`**. If it is passed a `Reader`, it doesn't  have a chance to properly use the detected encoding.

This means that for `XmlSource` instance leveraging `ReaderResource` the encoding is fully determined by the implicit `Codec` instance in scope. So using a `Path` or something else here as a source can lead to incorrectly decoded data.

The best solution here would be to switch to `InputResouce` as the main underlying abstraction, and only use a `ReaderResource` when there's no other choice.

**Comment by nrinaudo** [comment]
I’m on a business trip right now and a bit too busy to deal with this properly, but will take a look at this and at your PR as soon as my schedule becomes relatively sane again. Thanks for reporting!
